swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config: {}
x-a127-services: 
  quota:     
    provider: volos-quota-memory
    options:
      timeUnit: minute
      interval: 1
      allow: 2 
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    x-a127-apply: 
      quota: {}
      
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /loginAdminUser:
    # binds a127 app logic to a route
    x-swagger-router-controller: loginAdminUser
    x-a127-apply: {}
    get:
      description: login admin user
      # used as the method name of the controller
      operationId: login
      parameters:
        - name: username
          in: query
          description: login name
          required: false
          type: string
        - name: password
          in: query
          description: login password
          required: false
          type: string
      responses:
        "200":
          description: Success

        # responses may fall through to errors
        default:
          description: Error
  /signUpAdminUser:
    # binds a127 app logic to a route
    x-swagger-router-controller: signUpAdminUser
    x-a127-apply: {}
    post:
      description: sign up a new admin user
      # used as the method name of the controller
      operationId: signUpAdminUser
      parameters:
        - name: username
          in: formData
          description: login name
          required: false
          type: string
        - name: password
          in: formData
          description: login password
          required: false
          type: string
      responses:
        "200":
          description: Success

        # responses may fall through to errors
        default:
          description: Error
  /preSignUps:
    # binds a127 app logic to a route
    x-swagger-router-controller: preSignUps
    x-a127-apply: {}
    post:
      description: accept users to pre-sign-up for this app
      # used as the method name of the controller
      operationId: signUp
      parameters:
        - name: name
          in: formData
          description: name
          required: false
          type: string
        - name: email
          in: formData
          description: email
          required: false
          type: string
      responses:
        "200":
          description: Success

        # responses may fall through to errors
        default:
          description: Error

# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string

    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string

